name: Opcodes generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: riscv-builders
    steps:
    - uses: actions/checkout@v2
    - name: Install PyYAML
      run: |
        apt install -yq python3-pip
        pip config set global.break-system-packages true
        pip install -r requirements.txt
        pip install coverage
    - name: Run pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files
    - name: Generate
      run: coverage run ./parse.py -c -chisel -sverilog -rust -latex -spinalhdl -go "rv*" "unratified/rv*"
    - name: Check C output
      run: cat encoding.out.h  | cpp
    - name: Generate coverage
      run: coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v2
