name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: riscv-builders
    steps:
    - uses: actions/checkout@v2
    - name: Install PyYAML
      run: |
         apt install -yq python3-pip
         pip config set global.break-system-packages true
         pip install --break-system-packages -r requirements.txt
         pip install coverage
    - name: Test error outputs
      run: coverage run -m unittest -b
    - name: Generate coverage
      run: coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v2
